version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_NAME=micro_db
      - DB_USER=micro_user
      - DB_PASSWORD=micro_password
    depends_on:
      - db

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=db
      - DB_NAME=micro_db
      - DB_USER=micro_user
      - DB_PASSWORD=micro_password
    depends_on:
      - db

  order-service:
    build: ./order-service
    ports:
      - "5003:5003"
    environment:
      - DB_HOST=db
      - DB_NAME=micro_db
      - DB_USER=micro_user
      - DB_PASSWORD=micro_password
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=micro_db
      - POSTGRES_USER=micro_user
      - POSTGRES_PASSWORD=micro_password
    ports:
      - "5432:5432"