apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: IMAGE_PLACEHOLDER # This will be replaced by Jenkins
        ports:
        - containerPort: 5003
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "micro_db"
        - name: DB_USER
          value: "micro_user"
        - name: DB_PASSWORD
          value: "micro_password"