apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: ClusterIP # Changed from LoadBalancer for internal communication
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001