- name: Fetch kubeconfig from master
  hosts: k8s_master
  become: yes
  tasks:
    - name: Fetch kubeconfig file
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ lookup('env', 'WORKSPACE') }}/kubeconfig"
        flat: yes