- name: Install K8s prerequisites on all nodes
  hosts: k8s_master,k8s_workers
  become: yes
  tasks:
    - name: Enable kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Set up required sysctl params
      sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward

    - name: Install prerequisite packages
      package:
        name:
          - ca-certificates
          - python3
        state: present

    - name: Add Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
        dest: /etc/pki/rpm-gpg/kubernetes.gpg

    - name: Add Kubernetes YUM repo
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
        gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/kubernetes.gpg
        enabled: yes

    - name: Install Kubernetes components and containerd
      package:
        name:
          - kubelet
          - kubeadm
          - kubectl
          - containerd
        state: present

    - name: Enable and start containerd
      service:
        name: containerd
        state: started
        enabled: yes

    - name: Enable and start kubelet
      service:
        name: kubelet
        state: started
        enabled: yes
