---
- name: Install K8s prerequisites on all nodes
  hosts: k8s_master,k8s_workers
  become: yes
  tasks:
    - name: Install common packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - kubelet
          - kubeadm
          - containerd

    - name: Ensure containerd is running and enabled
      service:
        name: containerd
        state: started
        enabled: yes

- name: Configure K8s Master Node
  hosts: k8s_master
  become: yes
  tasks:
    - name: Install kubectl on master
      apt:
        name: kubectl
        state: present

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU

    - name: Set up kubectl for the ubuntu user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/ubuntu/.kube
        - cp /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        - chown ubuntu:ubuntu /home/ubuntu/.kube/config

    - name: Install Flannel Pod Network
      become: false
      command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    - name: Get the join command
      command: kubeadm token create --print-join-command
      register: join_command_result

    - name: Set join command as a fact
      set_fact:
        join_command: "{{ join_command_result.stdout }}"

- name: Configure K8s Worker Nodes
  hosts: k8s_workers
  become: yes
  tasks:
    - name: Join worker nodes to the cluster
      command: "{{ hostvars[groups['k8s_master'][0]].join_command }} --ignore-preflight-errors=NumCPU"
