---
- name: Install K8s prerequisites on all nodes
  hosts: k8s_master,k8s_workers
  become: yes
  tasks:
    - name: Install common packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - kubelet
          - kubeadm

- name: Configure K8s Master Node
  hosts: k8s_master
  become: yes
  tasks:
    - name: Install kubectl on master
      apt:
        name: kubectl
        state: present

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      set_fact:
        join_command: "{{ join_command.stdout }}"

- name: Configure K8s Worker Nodes
  hosts: k8s_workers
  become: yes
  tasks:
    - name: Join worker nodes to the cluster
      # The inventory name for the master is the IP address from the template
      command: "{{ hostvars[groups['k8s_master'][0]].join_command }}"

